/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppApiRouteImport } from './routes/app.api'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppBuildsRouteImport } from './routes/app.builds'
import { Route as AppCopilotRouteImport } from './routes/app.copilot'
import { Route as AppDocsRouteImport } from './routes/app.docs'
import { Route as AppEngineeringRouteImport } from './routes/app.engineering'
import { Route as AppExecutionsRouteImport } from './routes/app.executions'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppTestingRouteImport } from './routes/app.testing'
import { Route as AppTokensRouteImport } from './routes/app.tokens'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApiRoute = AppApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildsRoute = AppBuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppEngineeringRoute = AppEngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutionsRoute = AppExecutionsRouteImport.update({
  id: '/executions',
  path: '/executions',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTestingRoute = AppTestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => AppRoute,
} as any)
const AppTokensRoute = AppTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AppRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workflow': typeof WorkflowRoute
  '/app/api': typeof AppApiRoute
  '/app/billing': typeof AppBillingRoute
  '/app/builds': typeof AppBuildsRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/docs': typeof AppDocsRoute
  '/app/engineering': typeof AppEngineeringRoute
  '/app/executions': typeof AppExecutionsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/testing': typeof AppTestingRoute
  '/app/tokens': typeof AppTokensRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workflow': typeof WorkflowRoute
  '/app/api': typeof AppApiRoute
  '/app/billing': typeof AppBillingRoute
  '/app/builds': typeof AppBuildsRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/docs': typeof AppDocsRoute
  '/app/engineering': typeof AppEngineeringRoute
  '/app/executions': typeof AppExecutionsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/testing': typeof AppTestingRoute
  '/app/tokens': typeof AppTokensRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workflow': typeof WorkflowRoute
  '/app/api': typeof AppApiRoute
  '/app/billing': typeof AppBillingRoute
  '/app/builds': typeof AppBuildsRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/docs': typeof AppDocsRoute
  '/app/engineering': typeof AppEngineeringRoute
  '/app/executions': typeof AppExecutionsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/testing': typeof AppTestingRoute
  '/app/tokens': typeof AppTokensRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/platform'
    | '/pricing'
    | '/register'
    | '/sitemap.xml'
    | '/workflow'
    | '/app/api'
    | '/app/billing'
    | '/app/builds'
    | '/app/copilot'
    | '/app/docs'
    | '/app/engineering'
    | '/app/executions'
    | '/app/projects'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/testing'
    | '/app/tokens'
    | '/blog/$slug'
    | '/docs/$slug'
    | '/app/'
    | '/blog/'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/platform'
    | '/pricing'
    | '/register'
    | '/sitemap.xml'
    | '/workflow'
    | '/app/api'
    | '/app/billing'
    | '/app/builds'
    | '/app/copilot'
    | '/app/docs'
    | '/app/engineering'
    | '/app/executions'
    | '/app/projects'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/testing'
    | '/app/tokens'
    | '/blog/$slug'
    | '/docs/$slug'
    | '/app'
    | '/blog'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/platform'
    | '/pricing'
    | '/register'
    | '/sitemap.xml'
    | '/workflow'
    | '/app/api'
    | '/app/billing'
    | '/app/builds'
    | '/app/copilot'
    | '/app/docs'
    | '/app/engineering'
    | '/app/executions'
    | '/app/projects'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/testing'
    | '/app/tokens'
    | '/blog/$slug'
    | '/docs/$slug'
    | '/app/'
    | '/blog/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkflowRoute: typeof WorkflowRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DocsSlugRoute: typeof DocsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/api': {
      id: '/app/api'
      path: '/api'
      fullPath: '/app/api'
      preLoaderRoute: typeof AppApiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/builds': {
      id: '/app/builds'
      path: '/builds'
      fullPath: '/app/builds'
      preLoaderRoute: typeof AppBuildsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs': {
      id: '/app/docs'
      path: '/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/engineering': {
      id: '/app/engineering'
      path: '/engineering'
      fullPath: '/app/engineering'
      preLoaderRoute: typeof AppEngineeringRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/executions': {
      id: '/app/executions'
      path: '/executions'
      fullPath: '/app/executions'
      preLoaderRoute: typeof AppExecutionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/testing': {
      id: '/app/testing'
      path: '/testing'
      fullPath: '/app/testing'
      preLoaderRoute: typeof AppTestingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tokens': {
      id: '/app/tokens'
      path: '/tokens'
      fullPath: '/app/tokens'
      preLoaderRoute: typeof AppTokensRouteImport
      parentRoute: typeof AppRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppApiRoute: typeof AppApiRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBuildsRoute: typeof AppBuildsRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppDocsRoute: typeof AppDocsRoute
  AppEngineeringRoute: typeof AppEngineeringRoute
  AppExecutionsRoute: typeof AppExecutionsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTestingRoute: typeof AppTestingRoute
  AppTokensRoute: typeof AppTokensRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiRoute: AppApiRoute,
  AppBillingRoute: AppBillingRoute,
  AppBuildsRoute: AppBuildsRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppDocsRoute: AppDocsRoute,
  AppEngineeringRoute: AppEngineeringRoute,
  AppExecutionsRoute: AppExecutionsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppTestingRoute: AppTestingRoute,
  AppTokensRoute: AppTokensRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkflowRoute: WorkflowRoute,
  BlogSlugRoute: BlogSlugRoute,
  DocsSlugRoute: DocsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
